# Generated by Django 6.0.2 on 2026-04-14 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='availability_upon_delivery',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='overrun',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='required_by_norm',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='savings',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='total_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='total_spent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='upon_issuance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12),
        ),
    ]
