# Generated by Django 6.0.3 on 2026-04-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firetruck',
            table='fire_truck',
        ),
        migrations.AlterModelTable(
            name='firetruckwaybill',
            table='fire_truck_waybill',
        ),
        migrations.AlterModelTable(
            name='firetruckwaybillrecord',
            table='fire_truck_waybill_record',
        ),
        migrations.AlterModelTable(
            name='normsfiretruck',
            table='norms_fire_truck',
        ),
        migrations.AlterModelTable(
            name='normsoperatinghoursfiretruck',
            table='norms_operating_hours_fire_truck',
        ),
        migrations.AlterModelTable(
            name='normsoperatinghourspassengercar',
            table='norms_operating_hours_passenger_car',
        ),
        migrations.AlterModelTable(
            name='normspassengercars',
            table='norms_passenger_cars',
        ),
        migrations.AlterModelTable(
            name='normstechnicalmaintenance',
            table='norms_technical_maintenance',
        ),
        migrations.AlterModelTable(
            name='odometerfuelfiretruck',
            table='odometer_fuel_fire_truck',
        ),
        migrations.AlterModelTable(
            name='odometerfuelpassengercar',
            table='odometer_fuel_passenger_car',
        ),
        migrations.AlterModelTable(
            name='operatinghourscars',
            table='operating_hours_cars',
        ),
        migrations.AlterModelTable(
            name='passengercar',
            table='passenger_car',
        ),
        migrations.AlterModelTable(
            name='passengercarwaybill',
            table='passenger_car_waybill',
        ),
        migrations.AlterModelTable(
            name='passengercarwaybillrecord',
            table='passenger_car_waybill_record',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='technicalmaintenance',
            table='technical_maintenance',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
