# Generated by Django 6.0.2 on 2026-03-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_firetruckwaybillrecord_driving_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_create_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_create_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_permissisons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_update_permissisons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_update_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_permissisons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='view_drivers',
            field=models.BooleanField(default=False),
        ),
    ]
