# Generated by Django 6.0.2 on 2026-04-14 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fix_decimal_field_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='distance_km',
            field=models.PositiveIntegerField(editable=False, help_text='пробег, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_after',
            field=models.PositiveIntegerField(help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_before',
            field=models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, help_text='показания одометра, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_total_km',
            field=models.PositiveIntegerField(editable=False, help_text='всего пройдено км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_after',
            field=models.PositiveIntegerField(editable=False, help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_before',
            field=models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
