# Generated by Django 6.0.2 on 2026-04-15 16:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_expand_odometer_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetruckwaybill',
            name='overrun',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='firetruckwaybill',
            name='required_by_norm',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='firetruckwaybill',
            name='savings',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='firetruckwaybill',
            name='total_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='firetruckwaybill',
            name='total_spent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='distance_km',
            field=models.PositiveIntegerField(editable=False, help_text='пробег, км', validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used',
            field=models.DecimalField(decimal_places=3, help_text='фактически израсходовано, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_by_distance',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='Топливо по пробегу, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_normal',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по норме, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_with_pump',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='Топливо при работе с насосом, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_without_pump',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='Топливо при работе без насоса, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_after',
            field=models.PositiveIntegerField(help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_before',
            field=models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='time_with_pump',
            field=models.PositiveIntegerField(help_text='время работы с насосом, мин', validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='time_without_pump',
            field=models.PositiveIntegerField(help_text='время работы без насоса, мин', validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='normsoperatinghoursfiretruck',
            name='km_norm',
            field=models.DecimalField(decimal_places=3, help_text='норма по переводу в моточасы км(ч/км)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='normsoperatinghoursfiretruck',
            name='with_pump_norm',
            field=models.DecimalField(decimal_places=3, help_text='норма по переводу в моточасы с насосом(просто коэффициент)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='normsoperatinghourspassengercar',
            name='area_norm',
            field=models.DecimalField(decimal_places=3, help_text='норма по переводу в моточасы по области(ч/км)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='normsoperatinghourspassengercar',
            name='city_norm',
            field=models.DecimalField(decimal_places=3, help_text='норма по переводу в моточасы по городу(ч/км)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, help_text='показания одометра, км', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='availability_upon_delivery',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='overrun',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='required_by_norm',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='savings',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='total_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='total_spent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='passengercarwaybill',
            name='upon_issuance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_area_km',
            field=models.PositiveIntegerField(help_text='пройдено км по области', validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_city_km',
            field=models.PositiveIntegerField(help_text='пройдено км по городу', validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_total_km',
            field=models.PositiveIntegerField(editable=False, help_text='всего пройдено км', validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_area',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по области, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_city',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по городу, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_normal',
            field=models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по норме, л', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_after',
            field=models.PositiveIntegerField(editable=False, help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_before',
            field=models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='received',
            field=models.DecimalField(decimal_places=3, help_text='получено', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('100.000'))]),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='spent',
            field=models.DecimalField(decimal_places=3, help_text='израсходовано', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('100.000'))]),
        ),
    ]
